// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTlmlX30JLjiydM6REnmic1yNBswTYqE',
    appId: '1:984860647038:web:3bbe6e2c939386ea53022f',
    messagingSenderId: '984860647038',
    projectId: 'controle-abastecimento-18666',
    authDomain: 'controle-abastecimento-18666.firebaseapp.com',
    storageBucket: 'controle-abastecimento-18666.firebasestorage.app',
    measurementId: 'G-RRFTYKQBE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNZNomHSvx9j0qjOSUUtPZ3rMuP-dWJ78',
    appId: '1:984860647038:android:dd71f710a3a0892353022f',
    messagingSenderId: '984860647038',
    projectId: 'controle-abastecimento-18666',
    storageBucket: 'controle-abastecimento-18666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2YkZs_ruN8M50ZMjAu24RBzN_zsbB1o',
    appId: '1:984860647038:ios:604cdad238c0b2db53022f',
    messagingSenderId: '984860647038',
    projectId: 'controle-abastecimento-18666',
    storageBucket: 'controle-abastecimento-18666.firebasestorage.app',
    iosBundleId: 'com.example.gerenciamentoVeiculos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ2YkZs_ruN8M50ZMjAu24RBzN_zsbB1o',
    appId: '1:984860647038:ios:604cdad238c0b2db53022f',
    messagingSenderId: '984860647038',
    projectId: 'controle-abastecimento-18666',
    storageBucket: 'controle-abastecimento-18666.firebasestorage.app',
    iosBundleId: 'com.example.gerenciamentoVeiculos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTlmlX30JLjiydM6REnmic1yNBswTYqE',
    appId: '1:984860647038:web:abe2252c33c7403e53022f',
    messagingSenderId: '984860647038',
    projectId: 'controle-abastecimento-18666',
    authDomain: 'controle-abastecimento-18666.firebaseapp.com',
    storageBucket: 'controle-abastecimento-18666.firebasestorage.app',
    measurementId: 'G-Q7BYH20JZF',
  );
}
